"""Fingerprint manifest for a large data directory that stays out of git.

The files live on a drive or get regenerated by a pipeline; the manifest (bytes + sha256 per file, plus who/when/commit)
is committed, so anyone can answer "is my copy the same as yours?" at session start.
CLI: team-sync fingerprint [--check | --quick]
"""
import datetime as dt
import hashlib
import json
import subprocess

from .msg import t

SKIP = {'__pycache__', '.DS_Store'}


def _sha(p):
    h = hashlib.sha256()
    with open(p, 'rb') as f:
        for chunk in iter(lambda: f.read(1 << 20), b''):
            h.update(chunk)
    return h.hexdigest()


def _paths(cfg):
    fp = cfg.data.get('fingerprint') or {}
    root = cfg.repo / fp['root'] if fp.get('root') else None
    return root, cfg.repo / (fp.get('manifest') or 'data_manifest.json'), fp.get('root') or ''


def _walk(root):
    if not root or not root.is_dir():
        return {}
    return {str(p.relative_to(root)): p.stat().st_size for p in sorted(root.rglob('*'))
            if p.is_file() and not p.name.startswith('.') and not p.name.startswith('Icon') and not (set(p.parts) & SKIP)}


def build(cfg):
    root, manifest, label = _paths(cfg)
    if not root:
        raise SystemExit('fingerprint.root not set in team-sync.json')
    sizes = _walk(root)
    files = {rel: {'bytes': size, 'sha256': _sha(root / rel)} for rel, size in sizes.items()}
    head = subprocess.run(['git', 'rev-parse', '--short', 'HEAD'], cwd=cfg.repo, capture_output=True, text=True).stdout.strip() or None
    doc = {'root': label, 'generated_at': dt.datetime.now().isoformat(timespec='seconds'), 'by': cfg.who(), 'git_head': head,
           'file_count': len(files), 'total_bytes': sum(sizes.values()), 'files': files}
    manifest.write_text(json.dumps(doc, ensure_ascii=False, indent=1), encoding='utf-8')
    return doc


def check(cfg, quick=False):
    root, manifest, _ = _paths(cfg)
    if not manifest.exists():
        return None
    doc = json.loads(manifest.read_text(encoding='utf-8'))
    local, want = _walk(root), doc['files']
    added = sorted(set(local) - set(want)); removed = sorted(set(want) - set(local)); changed = []
    for rel in sorted(set(local) & set(want)):
        if local[rel] != want[rel]['bytes'] or (not quick and _sha(root / rel) != want[rel]['sha256']):
            changed.append(rel)
    return added, removed, changed, doc


def summary_line(cfg, quick=True):
    root, _, label = _paths(cfg)
    if not root:
        return ''
    if not root.is_dir():
        return t(cfg.lang, 'fp_absent', root=label)
    res = check(cfg, quick)
    if res is None:
        return t(cfg.lang, 'fp_none', root=label)
    a, r, c, doc = res
    if not (a or r or c):
        return t(cfg.lang, 'fp_ok', root=label, n=doc['file_count'], by=doc['by'], date=doc['generated_at'][:10])
    return t(cfg.lang, 'fp_diff', root=label, a=len(a), r=len(r), c=len(c), by=doc['by'], date=doc['generated_at'][:10])


def cli(ns, cfg):
    if ns.check or ns.quick:
        res = check(cfg, quick=ns.quick)
        if res is None:
            print('no manifest yet'); return 1
        a, r, c, _ = res
        print(summary_line(cfg, quick=ns.quick))
        for label, lst in (('added', a), ('missing', r), ('changed', c)):
            for rel in lst[:30]:
                print(f'  {label}: {rel}')
            if len(lst) > 30:
                print(f'  {label}: … {len(lst) - 30} more')
        return 1 if (a or r or c) else 0
    doc = build(cfg)
    print(f"✓ {doc['file_count']} files, {doc['total_bytes'] / 1e6:.0f} MB → {_paths(cfg)[1].relative_to(cfg.repo)}")
    return 0
