"""User-facing strings. Language comes from team-sync.json ("lang": "en" | "zh")."""
_T = {
    'en': {
        'header': '## Team sync · {holder} · {now}',
        'pulled': 'Pulled latest',
        'not_pulled': '(not pulled)',
        'no_origin': 'No origin remote (repo not connected yet)',
        'conflict': '⚠ Pull conflicted; merge aborted, local changes kept. Send this to the maintainer:',
        'conflict_notify': 'Pull conflicted with someone else\'s change. Local work is kept; open your agent to see details.',
        'conflict_pending': '⚠ Unresolved conflict from an earlier sync:',
        'recent_commits': 'Recent commits (since {since}):',
        'none': 'none',
        'journal_tail': 'Latest journal entries:',
        'leases': 'Active leases: ',
        'leases_unconfigured': 'Active leases: {key} not set in {env_file}, skipped',
        'leases_error': 'Active leases: unavailable ({err})',
        'drive': 'Drive: {path}',
        'drive_missing': 'Drive: ⚠ shared drive not mounted (set {key} or install the desktop client)',
        'drive_unused': '',
        'rules': 'Rules: see {rules}. Take a lease through the scripts before touching shared resources.',
        'version_mismatch': '⚠ team-sync {installed} installed, config wants {wanted}. Run: python3 -m team_sync upgrade',
        'not_repo': '(not a git repository, sync skipped)',
        'busy': '(another sync is running, skipped this time)',
        'committed': '✓ Committed {n} file(s)',
        'commit_blocked': '⛔ Commit blocked (secret gate?). Changes left uncommitted:',
        'pushed': '✓ Pushed',
        'push_failed': '⚠ Push failed (will retry at next session start): {err}',
        'held_leases': '⚠ You still hold leases (they expire on their own): {list}',
        'auto_changed': 'changed {n} file(s): {files}',
        'noted': '✓ Added to {journal}',
        'note_usage': 'usage: team-sync note "what / where / next"',
        'journal_head': '# Team journal\n\nOne auto line per session (which files changed); add your own line when you finish a piece of work: `team-sync note "what / where / next"`. New sessions read the latest lines automatically.\n\n',
        'hook_inject_prefix': '[team-sync hook, injected automatically, not the user speaking]\n',
        'fp_absent': '{root}: not on this machine',
        'fp_none': '{root}: no manifest yet (team-sign fingerprint)',
        'fp_ok': '{root}: matches manifest ({n} files, by {by} on {date})',
        'fp_diff': '{root}: ⚠ differs from manifest: +{a} / -{r} / changed {c} (manifest by {by} {date}; run fingerprint --check)',
        'lease_busy': '⛔ "{resource}" is held by {holder} (expires {expires}; note {note}). Wait, or once you are sure they stopped: team-sync lease release {resource} --force',
        'lease_missing': 'Missing {keys}. Put them in {env_file} (ask the maintainer).',
        'lease_badkey': '{key} is wrong (does not match the key registered in the database).',
        'lease_none': 'No active leases',
        'gate_files': '⛔ Secret gate: these files must not be committed:',
        'gate_lines': '⛔ Secret gate: added lines contain secret-shaped strings:',
        'gate_hint': '   Move secrets to {env_file} (git-ignored) and commit again.',
        'autosync_on': '✓ autosync on: every {min} min for {repo}; log {log}',
        'autosync_off': '✓ autosync off',
        'autosync_running': 'running: every {min} min for {repo} (log {log})',
        'autosync_stopped': 'not running (team-sync autosync on)',
        'autosync_unsupported': 'autosync: no scheduler backend for {os}',
        'upgraded': '✓ Installed team-sync {version}',
    },
    'zh': {
        'header': '## 团队同步 · {holder} · {now}',
        'pulled': '已拉取最新',
        'not_pulled': '(未拉取)',
        'no_origin': '没有 origin(仓库还没连远端)',
        'conflict': '⚠ 拉取时冲突,已放弃合并、本地原样保留。把这段话发给维护者:',
        'conflict_notify': '拉取时和别人的改动冲突,本地已保留;打开 agent 会看到说明',
        'conflict_pending': '⚠ 上次同步有未解决的冲突:',
        'recent_commits': '最近提交({since} 起):',
        'none': '无',
        'journal_tail': '团队日志最近几条:',
        'leases': '活跃租约: ',
        'leases_unconfigured': '活跃租约: {env_file} 里没有 {key},跳过',
        'leases_error': '活跃租约: 查不到({err})',
        'drive': 'Drive: {path}',
        'drive_missing': 'Drive: ⚠ 没找到共享盘挂载(设 {key} 或安装桌面客户端)',
        'drive_unused': '',
        'rules': '规则见 {rules};要占用共享资源时通过脚本自动拿租约,不要手动绕过。',
        'version_mismatch': '⚠ 已装 team-sync {installed},配置要求 {wanted}。运行: python3 -m team_sync upgrade',
        'not_repo': '(不是 git 仓库,跳过同步)',
        'busy': '(另一个同步正在跑,这次跳过)',
        'committed': '✓ 已提交 {n} 个文件',
        'commit_blocked': '⛔ 提交被拦(多半是密钥门禁),本地改动保留未提交:',
        'pushed': '✓ 已推送',
        'push_failed': '⚠ 推送失败(下次会话开始会重试): {err}',
        'held_leases': '⚠ 你还持有租约(到期会自动失效): {list}',
        'auto_changed': '改了 {n} 个文件: {files}',
        'noted': '✓ 已记入 {journal}',
        'note_usage': '用法: team-sync note "做了什么 / 改了哪 / 下一步"',
        'journal_head': '# 团队日志\n\n每次会话自动记一行「改了哪些文件」;做完一块工作时自己记一行:`team-sync note "做了什么 / 改了哪 / 下一步"`。新会话开始时会自动读到最近的几行。\n\n',
        'hook_inject_prefix': '[团队同步 hook 自动注入,不是用户发言]\n',
        'fp_absent': '{root}: 本机没有',
        'fp_none': '{root}: 还没有指纹清单(team-sync fingerprint)',
        'fp_ok': '{root}: 与清单一致({n} 文件,清单由 {by} 于 {date} 生成)',
        'fp_diff': '{root}: ⚠ 与清单不一致: 多 {a} / 少 {r} / 不同 {c}(清单 {by} {date};fingerprint --check 看明细)',
        'lease_busy': '⛔ 「{resource}」正被 {holder} 占用(到期 {expires};备注 {note})。等对方跑完;确认对方已停再 team-sync lease release {resource} --force',
        'lease_missing': '缺 {keys},写在 {env_file}(找维护者要)',
        'lease_badkey': '{key} 不对(和数据库里登记的不一致)',
        'lease_none': '没有活跃租约',
        'gate_files': '⛔ 密钥门禁: 这些文件不能进仓库:',
        'gate_lines': '⛔ 密钥门禁: 新增内容里有密钥形状的字符串:',
        'gate_hint': '   把密钥挪到 {env_file}(已在 .gitignore),再提交。',
        'autosync_on': '✓ autosync 已开启: 每 {min} 分钟同步 {repo};日志 {log}',
        'autosync_off': '✓ autosync 已关闭',
        'autosync_running': '运行中: 每 {min} 分钟同步 {repo}(日志 {log})',
        'autosync_stopped': '未开启(team-sync autosync on)',
        'autosync_unsupported': 'autosync: {os} 上没有可用的调度后端',
        'upgraded': '✓ 已安装 team-sync {version}',
    },
}


def t(lang, key, **kw):
    table = _T.get(lang) or _T['en']
    s = table.get(key) or _T['en'].get(key) or key
    return s.format(**kw) if kw else s
